[tool.poetry]
name = "first"
version = "0.1.0"
description = ""
authors = ["SergeY Kozin <qkb@bk.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
opencv-python = "^4.9.0.80"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
